# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-08 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, max_length=255, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('data_source', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('data_source', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
            ],
            options={
                'db_table': 'corpus',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('corpus_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('min_age', models.FloatField(blank=True, default=None, null=True)),
                ('max_age', models.FloatField(blank=True, default=None, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('group', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ses', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('custom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('token_order', models.IntegerField(blank=True, default=None, null=True)),
                ('replacement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('part_of_speech', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('stem', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('actual_phonology', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('model_phonology', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num_morphemes', models.IntegerField(blank=True, default=None, null=True)),
                ('english', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('clitic', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('utterance_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('corpus_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('speaker_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('speaker_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('speaker_role', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_tokens', to='db.Participant')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='TokenFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('speaker_role', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_token_frequencies', to='db.Participant')),
            ],
            options={
                'db_table': 'token_frequency',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
        migrations.CreateModel(
            name='TranscriptBySpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_role', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num_utterances', models.IntegerField(blank=True, default=None, null=True)),
                ('mlu_w', models.FloatField(blank=True, default=None, null=True)),
                ('mlu_m', models.FloatField(blank=True, default=None, null=True)),
                ('mtld', models.FloatField(blank=True, default=None, null=True)),
                ('hdd', models.FloatField(blank=True, default=None, null=True)),
                ('num_types', models.IntegerField(blank=True, default=None, null=True)),
                ('num_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('num_morphemes', models.IntegerField(blank=True, default=None, null=True)),
                ('collection_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_transcript_statistics', to='db.Participant')),
                ('transcript', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Transcript')),
            ],
            options={
                'db_table': 'transcript_by_speaker',
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(blank=True, db_index=True, default=None, max_length=1023, null=True)),
                ('stem', models.CharField(blank=True, db_index=True, default=None, max_length=1023, null=True)),
                ('actual_phonology', models.CharField(blank=True, db_index=True, default=None, max_length=1023, null=True)),
                ('model_phonology', models.CharField(blank=True, db_index=True, default=None, max_length=1023, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num_morphemes', models.IntegerField(blank=True, default=None, null=True)),
                ('num_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('utterance_order', models.IntegerField(blank=True, default=None, null=True)),
                ('corpus_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('part_of_speech', models.TextField(blank=True, default=None, null=True)),
                ('speaker_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('speaker_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('speaker_role', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('media_start', models.FloatField(blank=True, default=None, null=True)),
                ('media_end', models.FloatField(blank=True, default=None, null=True)),
                ('media_unit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Collection')),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Corpus')),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_utterances', to='db.Participant')),
                ('transcript', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Transcript')),
            ],
            options={
                'db_table': 'utterance',
            },
        ),
        migrations.AddField(
            model_name='tokenfrequency',
            name='transcript',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Transcript'),
        ),
        migrations.AddField(
            model_name='token',
            name='transcript',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Transcript'),
        ),
        migrations.AddField(
            model_name='token',
            name='utterance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Utterance'),
        ),
    ]
