# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DependentTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dependent_tier',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('ses', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('custom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(blank=True, max_length=255, null=True)),
                ('replacement', models.CharField(blank=True, max_length=255, null=True)),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('exceptions', models.CharField(blank=True, max_length=255, null=True)),
                ('interaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('room_layout', models.CharField(blank=True, max_length=255, null=True)),
                ('tape_location', models.CharField(blank=True, max_length=255, null=True)),
                ('time_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('time_start', models.CharField(blank=True, max_length=255, null=True)),
                ('transcription', models.CharField(blank=True, max_length=255, null=True)),
                ('warning', models.CharField(blank=True, max_length=255, null=True)),
                ('activities', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('new_episode', models.CharField(blank=True, max_length=255, null=True)),
                ('new_language', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
        migrations.RemoveField(
            model_name='child',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='session',
            name='child',
        ),
        migrations.RemoveField(
            model_name='word',
            name='utterance',
        ),
        migrations.RenameField(
            model_name='utterance',
            old_name='utterance_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='corpus_name',
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='target_child',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='act',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='gpx',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='sent_gloss',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='sit',
        ),
        migrations.AddField(
            model_name='corpus',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='contributor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='coverage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_accessavailability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_continent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_ethnicgroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_eventstructure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_interactivity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_involvement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_mediafiledescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_modalities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_planningtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_projectdescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_recordingconditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_socialcontext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='imdi_writtenresourcesubtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='rights',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='subject_olac_language',
            field=models.CharField(blank=True, db_column='subject.olac.language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='subject_olac_linguistic_field',
            field=models.CharField(blank=True, db_column='subject.olac.linguistic.field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='type_olacdiscourse_type',
            field=models.CharField(blank=True, db_column='type.olacdiscourse-type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='type_olaclinguistic_type',
            field=models.CharField(blank=True, db_column='type.olaclinguistic-type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='transcript',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus'),
        ),
        migrations.AddField(
            model_name='token',
            name='utterance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Utterance'),
        ),
        migrations.AddField(
            model_name='participant',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus'),
        ),
        migrations.AddField(
            model_name='participant',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Transcript'),
        ),
        migrations.AddField(
            model_name='dependenttier',
            name='utterance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Utterance'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='utterance',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Transcript'),
        ),
    ]
