# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170512_2235'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
    ]
