# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20170529_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='date',
            field=models.DateField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
