# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20170620_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 20, 6, 59, 57, 142564), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 20, 6, 59, 57, 145441), max_length=255, null=True),
        ),
    ]
