# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20170625_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='corpus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus'),
        ),
        migrations.AddField(
            model_name='token',
            name='transcript',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Transcript'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 25, 6, 57, 38, 332827), max_length=255, null=True),
        ),
    ]
