# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20170625_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 25, 11, 7, 35, 800470), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='gloss',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='relation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='stem',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
