# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20170625_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='part_of_speech',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 26, 9, 10, 31, 918694), max_length=255, null=True),
        ),
    ]
