# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20170626_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='transcript',
        ),
        migrations.AddField(
            model_name='token',
            name='speaker_age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='speaker_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='speaker_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='speaker_role',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='target_child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
        ),
        migrations.AddField(
            model_name='utterance',
            name='speaker_age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='speaker_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='speaker_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='speaker_role',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 27, 10, 15, 11, 908554), max_length=255, null=True),
        ),
    ]
