# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20170627_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 27, 10, 24, 27, 870025), max_length=255, null=True),
        ),
    ]
