# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20170627_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='max_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='min_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='target_child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 27, 10, 51, 19, 614004), max_length=255, null=True),
        ),
    ]
