# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20170627_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='target_child_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='speaker_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 27, 19, 42, 17, 774225), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='speaker_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
