# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20170628_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 28, 11, 34, 18, 926324), max_length=255, null=True),
        ),
    ]
