# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20170806_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='gloss',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='speaker_role',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
