# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20170822_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('num_occurrences', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('speaker_role', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('corpus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus')),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_token_frequencies', to='db.Participant')),
                ('transcript', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Transcript')),
            ],
            options={
                'db_table': 'token_frequency',
            },
        ),
        migrations.CreateModel(
            name='TranscriptBySpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_role', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('target_child_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_child_age', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('target_child_sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num_utterances', models.IntegerField(blank=True, default=None, null=True)),
                ('mlu', models.FloatField(blank=True, default=None, null=True)),
                ('num_types', models.IntegerField(blank=True, default=None, null=True)),
                ('num_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant')),
                ('target_child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_transcript_statistics', to='db.Participant')),
                ('transcript', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Transcript')),
            ],
            options={
                'db_table': 'transcript_by_speaker',
            },
        ),
        migrations.AlterField(
            model_name='token',
            name='target_child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tokens', to='db.Participant'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='target_child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_utterances', to='db.Participant'),
        ),
    ]
