# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20170902_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenfrequency',
            old_name='num_occurrences',
            new_name='count',
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='corpus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus'),
        ),
    ]
