# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20170902_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utterance',
            old_name='order',
            new_name='utterance_order',
        ),
        migrations.RemoveField(
            model_name='token',
            name='speaker_age',
        ),
        migrations.RemoveField(
            model_name='token',
            name='speaker_sex',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='speaker_age',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='speaker_sex',
        ),
        migrations.AddField(
            model_name='transcript',
            name='target_child_sex',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
