# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20171010_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='utterance_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
