# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20171012_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('flavor', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('who', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('utterance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Utterance')),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
    ]
