# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='media_end',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='media_start',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
