# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20171012_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='corpus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Corpus'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='speaker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='participant',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='token',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenfrequency',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='tokenfrequency',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='utterance',
            name='collection_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
