# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20171020_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='utterance',
        ),
        migrations.AddField(
            model_name='token',
            name='english',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='prefix',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='suffix',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
