# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20171023_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
