# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20171023_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='length',
            new_name='num_morphemes',
        ),
        migrations.RenameField(
            model_name='utterance',
            old_name='length',
            new_name='num_tokens',
        ),
        migrations.AddField(
            model_name='utterance',
            name='num_morphemes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
