# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_auto_20171023_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='languages',
            new_name='language',
        ),
        migrations.AddField(
            model_name='token',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenfrequency',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
