# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_auto_20171115_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, max_length=255, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
