# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='hdd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='mtld',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
