# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20180404_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='corpus_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='corpus_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='corpus_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='corpus_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
