# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_token_clitic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptbyspeaker',
            old_name='mlu',
            new_name='mlu_w',
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='mlu_m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transcriptbyspeaker',
            name='num_morphemes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
