# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_auto_20180419_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='part_of_speech',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='stem',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
